- hosts: jumpbox
  #roles:
 #    - osp-network
 #    - osp-keypair
 #    - osp-securitygroup
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: osp-instances
       vars_from: frontend.yaml
